# Use CentOS as the base image
FROM centos:latest

# Maintainer information
LABEL maintainer="gayathriraviraj84@gmail.com"

# Install necessary packages
RUN yum install -y httpd zip unzip

# Download the web template archive
ADD https://www.free-css.com/assets/files/free-css-templates/download/page290/restoran.zip /var/www/html/

# Set the working directory
WORKDIR /var/www/html

# Unzip the downloaded template
RUN unzip restoran.zip

# Move the extracted files to the current directory
RUN cp -r restoran/* .

# Clean up unnecessary files and folders
RUN rm -rf restoran restoran.zip

# Set the command to run Apache HTTP server
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]

# Expose necessary ports
EXPOSE 80 22
